name: flare_example
description: Simple Flare example.

dependencies:
  flutter:
    sdk: flutter
  cool_flare:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/

environment:
  sdk: ">=2.18.0 <4.0.0"