name: change_color
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cool_flare:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.18.0 <4.0.0"
