name: cool_flare
description: Vector design and runtime animation for Flutter (replacement for flare_flutter).
version: 3.0.2
homepage: https://github.com/cybex-dev/cool-flare

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.18.0 <4.0.0"
