name: favorite
description: A tappable Flare Widget.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cool_flare:
    path: ../..
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Light.ttf
  assets:
    - assets/
